/* eslint-disable react/react-in-jsx-scope */
import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/Header';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WMeddit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/reddit.ico" />
      </Head>
      <div>
        <div className='header'>
          <Header />
        </div>
        <div className='wrapper'></div>
        <div className='rightSide'></div>
      </div>
    </div>
  );
};

export default Home;
